fix: Respect contracts directory defined in adonisjrc.json
adonisjs/mail pull request #81
Opened 2022-11-19 21:12 UTC by TiBianMod

## Proposed changes

The `node ace configure @adonisjs/mail` ignores the defined `contracts` directory from the user inside `.adonisjrc.json`

This PR will respect the `contracts` directory defined by the user inside `.adonisjrc.json` and will fallback to default if not present.

## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/adonisjs/mail/blob/master/.github/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added necessary documentation (if appropriate)

## Further comments

@thetutlage point me to right direction for adding tests if necessary.
I can't find related tests for `node ace configure @adonisjs/mail`

2023-02-05 11:49 UTC, TiBianMod commented
ping @thetutlage

2023-02-06 14:18 UTC, RomainLanz requested changes

2023-02-06 14:18 UTC, RomainLanz commented on instructions.ts
> +  const contractsDir = app.directoriesMap.get('contracts') || 'contracts'
Can we use `path.join` instead?

```suggestion
  const contractsDirectory = app.directoriesMap.get('contracts') || 'contracts'
  const contractPath = join(contractsDirectory, 'mail.ts')
```

2023-02-06 14:18 UTC, RomainLanz commented on instructions.ts
> +  sink.logger.action('create').succeeded(`${contractsDir}/mail.ts`)
```suggestion
  sink.logger.action('create').succeeded(contractPath)
```

2023-02-08 01:40 UTC, TiBianMod commented
I have reverted the changes back to initial PR.
Let's keep consistency with the line [123-124](https://github.com/TiBianMod/adonisjs-mail/blob/develop/instructions.ts#L123)

** Also in your commit was an error on [line 131](https://github.com/adonisjs/mail/pull/81/commits/7c5b232de4ea6c0570a13a47706652333aaa1835) :-(

2023-08-11 03:47 UTC, merged

2023-08-11 03:47 UTC, thetutlage commented
@TiBianMod Thanks for the PR and sorry for taking that long :)

2023-08-11 11:00 UTC, TiBianMod commented
@thetutlage no problem mate 😄